### ISSUE TITLE
KeyMgmt node crashed when setting workerParams when there is a contract deployed

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-core#110]
**Describe the bug**
The Key Management node crashes when trying to set Worker Parameters *AND* there is at least one secret contract deployed in the network. When there are no contracts deployed, it works just fine.

**To Reproduce**
1. Launch the network
2. Deploy a secret contract
3. Trigger an epoch change

**Expected behavior**
The Key Management node should handle epoch changes with secret contracts deployed.

**Backtrace**
```
principal_1   | [? ] Blocks @ previous: 44, current: 54, next: 54 [? ]
principal_1   | [? ] New epoch found [? ]
principal_1   | The active workers: InputWorkerParams { block_number: 54, workers: [0xe43e4e5aeae608861b0d8d7c9533d22204b08181], stakes: [90000000000] }
principal_1   | Successfully decoded RLP worker parameters
principal_1   | Getting epoch for block number: None
principal_1   | Generated a nonce by incrementing the previous by 1 0x2
principal_1   | Generated random seed: 0xda927dd3be310c65d528cf260380ee33eeb95dbaf34516dd16a85f81ada03ce6
principal_1   | [+] Home dir is /root
principal_1   | Back from Ocall: /root/.enigma
principal_1   | Sealed document: "/root/.enigma/epoch/nonce.sealed" written successfully.
principal_1   | Sealed the epoch marker: "/root/.enigma/epoch/nonce.sealed"
principal_1   | Storing epoch: Epoch { nonce: 0x2, seed: 0xda927dd3be310c65d528cf260380ee33eeb95dbaf34516dd16a85f81ada03ce6, worker_params: InputWorkerParams { block_number: 0x36, workers: [0xe43e4e5aeae608861b0d8d7c9533d22204b08181], stakes: [0x14f46b0400] } }
principal_1   | Initial epoch stored successfully
principal_1   | Signed the message : 0xda927dd3be310c65d528cf260380ee33eeb95dbaf34516dd16a85f81ada03ce60000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e43e4e5aeae608861b0d8d7c9533d22204b08181000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000014f46b0400
principal_1   | Worker parameters set successfully
principal_1   | Waiting for setWorkerParams(54, 98863029089481325137085764549926061734584761540774669191620898061628498525414, Bytes([118, 62, 207, 186, 30, 44, 224, 4, 11, 72, 84, 96, 22, 220, 246, 238, 59, 178, 78, 79, 235, 41, 87, 232, 27, 152, 51, 68, 56, 20, 137, 38, 23, 177, 154, 137, 228, 204, 23, 233, 69, 210, 146, 25, 47, 70, 226, 149, 17, 107, 161, 124, 221, 84, 139, 194, 44, 221, 235, 100, 160, 126, 237, 75, 28]))
principal_1   | Got the receipt: Receipt { transaction_hash: 0x58699a02444f5bf5ede125ecdd40010d239cdf3b4f54ce87428d047d0bbd9c54, transaction_index: 0, block_hash: Some(0xa9074f9a0f823801dc3ec3097251cc6f1b3b12c597c80315442f291f9a4a9577), block_number: Some(55), cumulative_gas_used: 284154, gas_used: Some(284154), contract_address: None, logs: [Log { address: 0x59d3631c86bbe35ef041872d502f218a39fba150, topics: [0x4ac4fa4588e2c6fdaec0f375ac3b33fab7b69895fbb538347f8adb03164c5ddd], data: Bytes([218, 146, 125, 211, 190, 49, 12, 101, 213, 40, 207, 38, 3, 128, 238, 51, 238, 185, 93, 186, 243, 69, 22, 221, 22, 168, 95, 129, 173, 160, 60, 230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 62, 78, 90, 234, 230, 8, 134, 27, 13, 141, 124, 149, 51, 210, 34, 4, 176, 129, 129, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 244, 107, 4, 0]), block_hash: Some(0xa9074f9a0f823801dc3ec3097251cc6f1b3b12c597c80315442f291f9a4a9577), block_number: Some(55), transaction_hash: Some(0x58699a02444f5bf5ede125ecdd40010d239cdf3b4f54ce87428d047d0bbd9c54), transaction_index: Some(0), log_index: Some(0), transaction_log_index: None, log_type: None, removed: None }], status: Some(1), logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000 }
principal_1   | Parsed the WorkerParameterized event: Log { params: [LogParam { name: "seed", value: Uint(98863029089481325137085764549926061734584761540774669191620898061628498525414) }, LogParam { name: "firstBlockNumber", value: Uint(55) }, LogParam { name: "inclusionBlockNumber", value: Uint(54) }, LogParam { name: "workers", value: Array([Address(0xe43e4e5aeae608861b0d8d7c9533d22204b08181)]) }, LogParam { name: "stakes", value: Array([Uint(90000000000)]) }, LogParam { name: "nonce", value: Uint(2) }] }
principal_1   | Caching selected workers
principal_1   | The secret contract count: 1
principal_1   | The secret contract addresses: [Hash256([136, 152, 122, 247, 211, 94, 171, 202, 217, 89, 21, 185, 59, 253, 61, 43, 195, 48, 143, 6, 183, 25, 116, 120, 176, 223, 202, 38, 143, 4, 151, 220])]
principal_1   | Confirmed epoch with worker params: InputWorkerParams { block_number: 54, workers: [0xe43e4e5aeae608861b0d8d7c9533d22204b08181], stakes: [90000000000] }
principal_1   | Getting the selected worker for: Hash256([136, 152, 122, 247, 211, 94, 171, 202, 217, 89, 21, 185, 59, 253, 61, 43, 195, 48, 143, 6, 183, 25, 116, 120, 176, 223, 202, 38, 143, 4, 151, 220])
principal_1   | Found selected worker: 0xe43e4e5aeae608861b0d8d7c9533d22204b08181 for contract: Hash256([136, 152, 122, 247, 211, 94, 171, 202, 217, 89, 21, 185, 59, 253, 61, 43, 195, 48, 143, 6, 183, 25, 116, 120, 176, 223, 202, 38, 143, 4, 151, 220])
principal_1   | First selected worker inserted
principal_1   | Replacing EpochMaker mutex: Some(EpochState { seed: 98863029089481325137085764549926061734584761540774669191620898061628498525414, sig: Bytes([118, 62, 207, 186, 30, 44, 224, 4, 11, 72, 84, 96, 22, 220, 246, 238, 59, 178, 78, 79, 235, 41, 87, 232, 27, 152, 51, 68, 56, 20, 137, 38, 23, 177, 154, 137, 228, 204, 23, 233, 69, 210, 146, 25, 47, 70, 226, 149, 17, 107, 161, 124, 221, 84, 139, 194, 44, 221, 235, 100, 160, 126, 237, 75, 28]), nonce: 2, confirmed_state: Some(ConfirmedEpochState { selected_workers: {Hash256([136, 152, 122, 247, 211, 94, 171, 202, 217, 89, 21, 185, 59, 253, 61, 43, 195, 48, 143, 6, 183, 25, 116, 120, 176, 223, 202, 38, 143, 4, 151, 220]): 0xe43e4e5aeae608861b0d8d7c9533d22204b08181}, block_number: 55 }) })
principal_1   | Replaced EpochMaker: Some(EpochState { seed: 71872192111550777480056716804724733771791342950088026133095723568720506161118, sig: Bytes([176, 186, 92, 3, 145, 231, 238, 242, 10, 100, 159, 245, 140, 49, 103, 94, 151, 87, 54, 54, 216, 28, 151, 156, 252, 50, 219, 151, 161, 49, 8, 51, 9, 234, 1, 65, 15, 47, 5, 218, 145, 10, 66, 161, 6, 59, 125, 207, 217, 123, 7, 225, 18, 75, 119, 35, 133, 155, 172, 155, 139, 108, 151, 228, 28]), nonce: 1, confirmed_state: Some(ConfirmedEpochState { selected_workers: {}, block_number: 44 }) }) with: Some(EpochState { seed: 98863029089481325137085764549926061734584761540774669191620898061628498525414, sig: Bytes([118, 62, 207, 186, 30, 44, 224, 4, 11, 72, 84, 96, 22, 220, 246, 238, 59, 178, 78, 79, 235, 41, 87, 232, 27, 152, 51, 68, 56, 20, 137, 38, 23, 177, 154, 137, 228, 204, 23, 233, 69, 210, 146, 25, 47, 70, 226, 149, 17, 107, 161, 124, 221, 84, 139, 194, 44, 221, 235, 100, 160, 126, 237, 75, 28]), nonce: 2, confirmed_state: Some(ConfirmedEpochState { selected_workers: {Hash256([136, 152, 122, 247, 211, 94, 171, 202, 217, 89, 21, 185, 59, 253, 61, 43, 195, 48, 143, 6, 183, 25, 116, 120, 176, 223, 202, 38, 143, 4, 151, 220]): 0xe43e4e5aeae608861b0d8d7c9533d22204b08181}, block_number: 55 }) })
principal_1   | [+] Home dir is /root
principal_1   | thread 'main' panicked at 'Unable to set worker params. Please recover manually.: ErrorMessage { msg: Error("key must be a string", line: 0, column: 0)
principal_1   | 
principal_1   | stack backtrace:
principal_1   |    0: failure::backtrace::internal::InternalBacktrace::new::hf867e4e9d99c9480 (0x558bc8a457ce)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
principal_1   |    1: failure::backtrace::Backtrace::new::hcdbeb17bff96e963 (0x558bc8a4529d)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
principal_1   |    2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h6d7672ad92dfd3ba (0x558bc812797f)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
principal_1   |    3: <failure::error::Error as core::convert::From<F>>::from::h525b60e188527c7b (0x558bc8104f82)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
principal_1   |    4: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::write_epoch_state::h8e2f9e2322a7dd4e (0x558bc7b8bfe9)
principal_1   |              at src/epoch_u/epoch_provider.rs:76
principal_1   |    5: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_epoch_state::{{closure}}::h555911303c9ca161 (0x558bc7bfe872)
principal_1   |              at src/epoch_u/epoch_provider.rs:124
principal_1   |    6: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_epoch_state::h740704e224a7dd9b (0x558bc7b8d72d)
principal_1   |              at src/epoch_u/epoch_provider.rs:114
principal_1   |    7: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_worker_params::he44c45d6af0cdaf6 (0x558bc7bfb2fc)
principal_1   |              at src/epoch_u/epoch_provider.rs:183
principal_1   |    8: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks::{{closure}}::hda2417817ce2c3af (0x558bc7c227a0)
principal_1   |              at src/boot_network/principal_utils.rs:43
principal_1   |    9: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks::hbe7deceee6e8781a (0x558bc7bd6387)
principal_1   |              at src/boot_network/principal_utils.rs:23
principal_1   |   10: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::{{closure}}::h8acaeebcb0573f67 (0x558bc7ca9bdb)
principal_1   |              at src/boot_network/principal_manager.rs:230
principal_1   |   11: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::h6278e3242b8b4a55 (0x558bc7ca8e9a)
principal_1   |              at src/boot_network/principal_manager.rs:206
principal_1   |   12: enigma_principal_app::cli::app::start::{{closure}}::had69debde7541a25 (0x558bc7c7cc7a)
principal_1   |              at src/cli/app.rs:78
principal_1   |   13: enigma_principal_app::cli::app::start::hb6e3b5c54b1e8c73 (0x558bc7be34c3)
principal_1   |              at src/cli/app.rs:14
principal_1   |   14: enigma_principal_app::main::h87b6fd8c6645f40f (0x558bc7b83aaa)
principal_1   |              at src/main.rs:65
principal_1   |   15: std::rt::lang_start::{{closure}}::h03ef5a4683367f1c (0x558bc7c9ce2f)
principal_1   |              at libstd/rt.rs:74
principal_1   |   16: std::rt::lang_start_internal::{{closure}}::hdc2a896aeffb5179 (0x558bc8b18142)
principal_1   |              at libstd/rt.rs:59
principal_1   |       std::panicking::try::do_call::h5a4eb2ce70a501f5
principal_1   |              at libstd/panicking.rs:310
principal_1   |   17: __rust_maybe_catch_panic (0x558bc8b3a9e9)
principal_1   |              at libpanic_unwind/lib.rs:102
principal_1   |   18: std::panicking::try::h97436c380f30f437 (0x558bc8b1a655)
principal_1   |              at libstd/panicking.rs:289
principal_1   |       std::panic::catch_unwind::h9c28ef6e0c478c5d
principal_1   |              at libstd/panic.rs:392
principal_1   |       std::rt::lang_start_internal::h6abd6befa9748e41
principal_1   |              at libstd/rt.rs:58
principal_1   |   19: std::rt::lang_start::hea4f08f84bbd1ba1 (0x558bc7c9ce07)
principal_1   |              at libstd/rt.rs:74
principal_1   |   20: main (0x558bc7b83c89)
principal_1   |   21: __libc_start_main (0x7f1ea3867b96)
principal_1   |   22: _start (0x558bc7b73b59)
principal_1   |   23: <unknown> (0x0) }
principal_1   | 
principal_1   | stack backtrace:
principal_1   |    0: failure::backtrace::internal::InternalBacktrace::new::hf867e4e9d99c9480 (0x558bc8a457ce)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
principal_1   |    1: failure::backtrace::Backtrace::new::hcdbeb17bff96e963 (0x558bc8a4529d)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
principal_1   |    2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h9fb934c840892e71 (0x558bc7b8f6b7)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
principal_1   |    3: <failure::error::Error as core::convert::From<F>>::from::h1e03dd5803028b7f (0x558bc7be328c)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
principal_1   |    4: failure::error_message::err_msg::hc654fd682723dbdf (0x558bc7c965b0)
principal_1   |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
principal_1   |    5: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_epoch_state::{{closure}}::h555911303c9ca161 (0x558bc7bfe95e)
principal_1   |              at src/epoch_u/epoch_provider.rs:126
principal_1   |    6: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_epoch_state::h740704e224a7dd9b (0x558bc7b8d72d)
principal_1   |              at src/epoch_u/epoch_provider.rs:114
principal_1   |    7: enigma_principal_app::epoch_u::epoch_provider::EpochProvider::set_worker_params::he44c45d6af0cdaf6 (0x558bc7bfb2fc)
principal_1   |              at src/epoch_u/epoch_provider.rs:183
principal_1   |    8: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks::{{closure}}::hda2417817ce2c3af (0x558bc7c227a0)
principal_1   |              at src/boot_network/principal_utils.rs:43
principal_1   |    9: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks::hbe7deceee6e8781a (0x558bc7bd6387)
principal_1   |              at src/boot_network/principal_utils.rs:23
principal_1   |   10: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::{{closure}}::h8acaeebcb0573f67 (0x558bc7ca9bdb)
principal_1   |              at src/boot_network/principal_manager.rs:230
principal_1   |   11: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::h6278e3242b8b4a55 (0x558bc7ca8e9a)
principal_1   |              at src/boot_network/principal_manager.rs:206
principal_1   |   12: enigma_principal_app::cli::app::start::{{closure}}::had69debde7541a25 (0x558bc7c7cc7a)
principal_1   |              at src/cli/app.rs:78
principal_1   |   13: enigma_principal_app::cli::app::start::hb6e3b5c54b1e8c73 (0x558bc7be34c3)
principal_1   |              at src/cli/app.rs:14
principal_1   |   14: enigma_principal_app::main::h87b6fd8c6645f40f (0x558bc7b83aaa)
principal_1   |              at src/main.rs:65
principal_1   |   15: std::rt::lang_start::{{closure}}::h03ef5a4683367f1c (0x558bc7c9ce2f)
principal_1   |              at libstd/rt.rs:74
principal_1   |   16: std::rt::lang_start_internal::{{closure}}::hdc2a896aeffb5179 (0x558bc8b18142)
principal_1   |              at libstd/rt.rs:59
principal_1   |       std::panicking::try::do_call::h5a4eb2ce70a501f5
principal_1   |              at libstd/panicking.rs:310
principal_1   |   17: __rust_maybe_catch_panic (0x558bc8b3a9e9)
principal_1   |              at libpanic_unwind/lib.rs:102
principal_1   |   18: std::panicking::try::h97436c380f30f437 (0x558bc8b1a655)
principal_1   |              at libstd/panicking.rs:289
principal_1   |       std::panic::catch_unwind::h9c28ef6e0c478c5d
principal_1   |              at libstd/panic.rs:392
principal_1   |       std::rt::lang_start_internal::h6abd6befa9748e41
principal_1   |              at libstd/rt.rs:58
principal_1   |   19: std::rt::lang_start::hea4f08f84bbd1ba1 (0x558bc7c9ce07)
principal_1   |              at libstd/rt.rs:74
principal_1   |   20: main (0x558bc7b83c89)
principal_1   |   21: __libc_start_main (0x7f1ea3867b96)
principal_1   |   22: _start (0x558bc7b73b59)
principal_1   |   23: <unknown> (0x0)', libcore/result.rs:1009:5
principal_1   | stack backtrace:
principal_1   |    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
principal_1   |              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
principal_1   |    1: std::sys_common::backtrace::print
principal_1   |              at libstd/sys_common/backtrace.rs:71
principal_1   |              at libstd/sys_common/backtrace.rs:59
principal_1   |    2: std::panicking::default_hook::{{closure}}
principal_1   |              at libstd/panicking.rs:211
principal_1   |    3: std::panicking::default_hook
principal_1   |              at libstd/panicking.rs:227
principal_1   |    4: std::panicking::rust_panic_with_hook
principal_1   |              at libstd/panicking.rs:476
principal_1   |    5: std::panicking::continue_panic_fmt
principal_1   |              at libstd/panicking.rs:390
principal_1   |    6: rust_begin_unwind
principal_1   |              at libstd/panicking.rs:325
principal_1   |    7: core::panicking::panic_fmt
principal_1   |              at libcore/panicking.rs:77
principal_1   |    8: core::result::unwrap_failed
principal_1   |              at libcore/macros.rs:26
principal_1   |    9: <core::result::Result<T, E>>::expect
principal_1   |              at libcore/result.rs:835
principal_1   |   10: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks::{{closure}}
principal_1   |              at src/boot_network/principal_utils.rs:43
principal_1   |   11: <enigma_tools_u::web3_utils::enigma_contract::EnigmaContract as enigma_principal_app::boot_network::principal_utils::Principal>::watch_blocks
principal_1   |              at src/boot_network/principal_utils.rs:23
principal_1   |   12: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::{{closure}}
principal_1   |              at src/boot_network/principal_manager.rs:230
principal_1   |   13: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run
principal_1   |              at src/boot_network/principal_manager.rs:206
principal_1   |   14: enigma_principal_app::cli::app::start::{{closure}}
principal_1   |              at src/cli/app.rs:78
principal_1   |   15: enigma_principal_app::cli::app::start
principal_1   |              at src/cli/app.rs:14
principal_1   |   16: enigma_principal_app::main
principal_1   |              at src/main.rs:65
principal_1   |   17: std::rt::lang_start::{{closure}}
principal_1   |              at libstd/rt.rs:74
principal_1   |   18: std::panicking::try::do_call
principal_1   |              at libstd/rt.rs:59
principal_1   |              at libstd/panicking.rs:310
principal_1   |   19: __rust_maybe_catch_panic
principal_1   |              at libpanic_unwind/lib.rs:102
principal_1   |   20: std::rt::lang_start_internal
principal_1   |              at libstd/panicking.rs:289
principal_1   |              at libstd/panic.rs:392
principal_1   |              at libstd/rt.rs:58
principal_1   |   21: std::rt::lang_start
principal_1   |              at libstd/rt.rs:74
principal_1   |   22: main
principal_1   |   23: __libc_start_main
principal_1   |   24: _start
```

**Comment by fredfortier** [comment]
Closing based on PR #112.
